# Generated by Django 4.1 on 2022-11-21 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="group",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="job",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="phone",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="逻辑删除"),
        ),
        migrations.CreateModel(
            name="UserDetailInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="手机号码")),
                ("group", models.CharField(max_length=5, verbose_name="组别")),
                ("job", models.CharField(max_length=5, verbose_name="职务")),
                (
                    "email",
                    models.EmailField(max_length=254, null=True, verbose_name="邮箱"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.userinfo",
                        verbose_name="关联外键",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户详细信息",
                "verbose_name_plural": "用户详细信息",
                "db_table": "402_users_details",
            },
        ),
        migrations.CreateModel(
            name="RecordsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starttime", models.DateTimeField(verbose_name="开始时间")),
                ("endtime", models.DateTimeField(verbose_name="结束时间")),
                ("choice", models.CharField(max_length=9, verbose_name="会议类型")),
                (
                    "test",
                    models.CharField(max_length=200, null=True, verbose_name="补充说明信息"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="逻辑删除")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="api.userinfo",
                        verbose_name="姓名",
                    ),
                ),
            ],
            options={
                "verbose_name": "预约记录",
                "verbose_name_plural": "预约记录",
                "db_table": "402_user_records",
            },
        ),
    ]
