# Generated by Django 4.1 on 2022-11-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_userinfo_group_remove_userinfo_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetailinfo",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="逻辑删除"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="certification",
            field=models.BooleanField(default=False, verbose_name="是否认证"),
        ),
    ]
