# Generated by Django 4.1 on 2022-11-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userdetailinfo_is_delete_userinfo_certification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recordsinfo",
            old_name="test",
            new_name="text",
        ),
    ]
