# Generated by Django 3.1 on 2022-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_test_recordsinfo_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_is_key', models.CharField(max_length=200, null=True, verbose_name='钥匙在哪儿')),
            ],
            options={
                'verbose_name': '钥匙在哪儿',
                'verbose_name_plural': '钥匙在哪儿',
                'db_table': 'where_is_key',
            },
        ),
        migrations.AlterField(
            model_name='recordsinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetailinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
